### ISSUE TITLE
I am madly in love with fungus.

### ISSUE THREAD

**Issue by PassTheMycelium** [Esophose/PlayerParticles-2#1]
Hello!

Just, as a possible request, could mycelium particles be added to the plugin?
I would be the happiest little mooshroom if they were.

Yours Sporadically, 
PassThePeppers

**Comment by Esophose** [comment]
These particles already exist in the plugin, actually. The type "depthsuspend" is for the void particles, but doubles as the mycelium particles since they are the exact same.

**Comment by PassTheMycelium** [comment]
Thanks! Much love.
<3
